// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YugiohCard.Data;

#nullable disable

namespace YugiohCard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YugiohCard.Models.MonsterCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ATK")
                        .HasColumnType("int");

                    b.Property<int>("DEF")
                        .HasColumnType("int");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("Link")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Race")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MonsterCards");

                    b.HasData(
                        new
                        {
                            Id = "RA04-EN001",
                            ATK = 2500,
                            DEF = 2100,
                            Effect = "The ultimate wizard in terms of attack and defense.",
                            ImageUrl = "https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4041",
                            Level = 7,
                            Name = "Dark Magician",
                            Race = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = "BLC1-EN039",
                            ATK = 2500,
                            DEF = 2000,
                            Effect = "2 Level 4 monsters \n When a monster declares an attack: You can detach 1 material from this card; negate the attack. If this card is targeted for an attack, while it has no material: Destroy this card.",
                            ImageUrl = "https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=9575",
                            Name = "Number 39: Utopia",
                            Race = 1,
                            Rank = 4,
                            Type = 5
                        },
                        new
                        {
                            Id = "DUDE-EN022",
                            ATK = 2600,
                            DEF = 0,
                            Effect = "2+ monsters",
                            ImageUrl = "https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=13090",
                            Link = 3,
                            Name = "Gaia Saber, the Lightning Shadow",
                            Race = 7,
                            Type = 6
                        });
                });

            modelBuilder.Entity("YugiohCard.Models.SpellCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpellCards");

                    b.HasData(
                        new
                        {
                            Id = "LOB-EN119",
                            Effect = "Draw 2 cards.",
                            ImageUrl = "https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4844",
                            Name = "Pot of Greed",
                            Type = 0
                        },
                        new
                        {
                            Id = "MGED-EN047",
                            Effect = "If your opponent controls more monsters than you do, your opponent cannot activate monster effects or declare an attack. If you control more monsters than your opponent does, you cannot activate monster effects or declare an attack. Once per turn, during the End Phase, if both players control the same number of monsters: Destroy this card.",
                            ImageUrl = "https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=14314",
                            Name = "Mystic Mine",
                            Type = 4
                        });
                });

            modelBuilder.Entity("YugiohCard.Models.TrapCard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrapCards");

                    b.HasData(
                        new
                        {
                            Id = "RA03-EN093",
                            Effect = "When an opponent's monster declares an attack: Destroy all your opponent's Attack Position monsters.",
                            ImageUrl = "https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4887",
                            Name = "Mirror Force",
                            Type = 0
                        },
                        new
                        {
                            Id = "RA02-EN075",
                            Effect = "When a monster(s) would be Summoned, OR a Spell/Trap Card is activated: Pay half your LP; negate the Summon or activation, and if you do, destroy that card.",
                            ImageUrl = "https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=4861",
                            Name = "Solemn Judgment",
                            Type = 2
                        });
                });

            modelBuilder.Entity("YugiohCard.Models.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefeshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
